### ISSUE TITLE
Chatroom not integrating with Rasa bot with 0.11 version

### ISSUE THREAD

**Issue by hnithyanandam** [scalableminds/chatroom#103]
I tried using

```
rasa-core==0.11.1
rasa-core-sdk==0.11.0
rasa-nlu==0.13.2
```
My credentials.yml file is (I created a folder rasa_utils and posted the file in the github there)

```
rasa_utils.bot_server_channel.BotServerInputChannel:
#pass
```
i am running the server using this command.
`python -m rasa_core.run --enable_api -d models/dialogue -u models/current/nlu --port 5005 --endpoints endpoints.yml --credentials credentials.yml --cors "*"`

i tried with rest endpoint and that is working . Please find the repo - [https://github.com/hnithyanandam/samplerasabot](url)

**Comment by jstriebel** [comment]
What is the actual error you are getting? What exactly is not integrating?

**Comment by hnithyanandam** [comment]
I was not able to connect to the UI itself. After upgrading Rasa version , error got fixed
