### ISSUE TITLE
issue for the new version of rasa

### ISSUE THREAD

**Issue by Robertjbc** [scalableminds/chatroom#104]
hello friend i have a issue about the chatroom in the new version of rasa=1.0.1...

i'll try to connect the chat in a  new version and when i test it they give me a error 

the error say what the BotServerInputChannel is misspelled but i think is a error from rasa

if you can help me i'll appreciate it 

 regards 😉

**Comment by hotzenklotz** [comment]
Rasa most likely restructured their code quite a bit for the launch of version `1.x`. 

If you feel adventurous you can use the chatroom component from the branch `rest-channel` which uses the Rasa REST channel API instead of our custom connector for simplicity. Check out the (open) pull request. #102

**Comment by Robertjbc** [comment]
i'll wait that you update the custom connector, while
 how i can connect the rest channel with my rasa bot, what are the step i have to follow

regards 😉

**Comment by hotzenklotz** [comment]
Check the readme in PR #102

**Comment by Robertjbc** [comment]
thanks for  yours answers but a have a error

`[2019-05-25 12:41:43 -0400] [1644] [ERROR] Exception occurred while handling uri: 'http://localhost:5005/webhooks/chatroom/conversations/889c6c8d-19b5-4168-ada7-592ff2373100/log?nocache=1558802503672'
Traceback (most recent call last):
  File "c:\users\capitalminds\appdata\local\programs\python\python36\lib\site-packages\sanic\app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "c:\users\capitalminds\appdata\local\programs\python\python36\lib\site-packages\sanic\router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "c:\users\capitalminds\appdata\local\programs\python\python36\lib\site-packages\sanic\router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url)
sanic.exceptions.NotFound: Requested URL /webhooks/chatroom/conversations/889c6c8d-19b5-4168-ada7-592ff2373100/log not found)`

i'll put the script in a blank html
and give me that error

**Comment by hotzenklotz** [comment]
If you are using the code fromn PR #102, then it looks like you are still using the (old) Javascript with the new REST channel. Make sure to load the right version of the chatroom: 

`https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@rest-channel/dist/Chatroom.js` 

Note, `@rest-channel` refers to the current branch name (=version). We will most likely merge the PR over the next days and publish these changes under version `0.10.0`.

**Comment by Robertjbc** [comment]
thanks you a lot i'll test it and work perfect 

so you say your publish the version 0.10.0 with rest channel in a few days ?

regards

**Comment by hotzenklotz** [comment]
I published version `0.10.0` yesterday. Should be able to use it. Let me know if you find any bugs, etc.

**Comment by Robertjbc** [comment]
thanks  you a lot, i'll test it and i write you if a find a bugs or something like thats 

regards 

😉
