### ISSUE TITLE
How can i send HTML formatted response 

### ISSUE THREAD

**Issue by hnithyanandam** [scalableminds/chatroom#105]
i am sending HTML formatted text as response for Eg `<B>text</B>`. I am not able to see that format in the UI. It is coming as it is. How can i set response as formatted text.

**Comment by hotzenklotz** [comment]
HTML formatting is not supported. You can use Markdown formatting for text instead.

**Comment by hnithyanandam** [comment]
Can you please provide some samples for mark down for Bold , etc

**Comment by hnithyanandam** [comment]
Thanks , was able to use markdown .It would be great if it supports html
