### ISSUE TITLE
Increase duration of bubble on UI

### ISSUE THREAD

**Issue by LKiera** [scalableminds/chatroom#106]
I have connected it with rasa, but sometimes when the bubble animation stops, it feels like the bot is not responding, but it just taking it's time for processing. So, is there any way to increase it's duration or maybe stop as soon as getting a response from rasa core

**Comment by hotzenklotz** [comment]
Yes, you can change that. Use the attribute `waitingTimeout`. The default is 5000ms (5s). E.g.

```
<script type="text/javascript">
window.chatroom = new window.Chatroom({
  container: document.querySelector(".chat-container"),
  host: "http://localhost:5005",
  waitingTimeout: 10000,
...
});
window.chatroom.openChat();
</script>
```

**Comment by LKiera** [comment]
Thanks! That worked
