### ISSUE TITLE
I want to contribute a pull request but I'm getting 403 when pushing to a feature branch

### ISSUE THREAD

**Issue by nicholasbulka** [scalableminds/chatroom#111]
Are you accepting pull requests at the moment? Or is this a problem with my configuration somehow?

**Comment by hotzenklotz** [comment]
Hi @nicholasbulka,

thanks for your interest in the project. We would be happy accept your PR. You can't, however, directly push a feature branch to our repository. The GitHub contribution model works a bit different:

Please, fork the repository first and make changes to your fork. Then open the PR from your fork to our "main" repository. See this guide for more information: https://guides.github.com/activities/forking/
