### ISSUE TITLE
Chatroom "eats" some first letters for non-English language

### ISSUE THREAD

**Issue by GraphGrailAi** [scalableminds/chatroom#120]
I faced an issue: if i write a Cyrillic words that begins from "в" (example word "велосипед", en: bicycle becomes "елосипед") letter chatroom seems to "eat" this first letter and in chat history i see this word without first letter. Other letters seems ok.

This cause the following: Rasa refuse to understand this intent.
Seems this is javascript issue related to characters encoding, not Rasa itself.

**Comment by hotzenklotz** [comment]
@GraphGrailAi Thanks for bringing this to our attention. We are happy to accept pull request to fix this. I don't have much experience with character encoding for Cyrillic so feel free to suggest a fix. 

Is this issue present in all modern browsers or just one particular one?

**Comment by GraphGrailAi** [comment]
> Is this issue present in all modern browsers or just one particular one?

In all browsers. If letter is not first it is printed correctly

**Comment by GraphGrailAi** [comment]
Hm. latest js from cdn fixed this. I close
