### ISSUE TITLE
Getting weird chars on response

### ISSUE THREAD

**Issue by rileythiessen** [scalableminds/chatroom#121]
Hello, I was wondering if anyone could help me. I'm getting weird characters on the response I presume it has something to do with the js acting up?

![image](https://user-images.githubusercontent.com/46572857/72762000-94c70380-3ba3-11ea-95ee-a730515fa5c0.png)

**Comment by hotzenklotz** [comment]
It's a font issue. Apparently your system does not support the loading animation: a bunch of bouncing dots.  

Check the dev tools which fonts it is loading that results in these characters.

**Comment by rileythiessen** [comment]
Thanks for the quick reply, I was wondering if you could point me in the correct direction to find the dev tools... thanks

**Comment by hotzenklotz** [comment]
> Thanks for the quick reply, I was wondering if you could point me in the correct direction to find the dev tools... thanks

I meant your browser's dev tools. E.g. Chrome: https://developers.google.com/web/tools/chrome-devtools
