### ISSUE TITLE
Strange language behaviour

### ISSUE THREAD

**Issue by dmedved90** [scalableminds/chatroom#122]
Hi, 
When I change the language to Croatian with "hr-HR", I noticed strange behavior.
In some cases, everything is working perfect but in some environments Chatroom "defaults" to English, TTS is on English.
I all test cases I have the latest Chrome installed, identical Windows 10 installations with identical language settings on laptops. Everything is on the local network.
Any idea where is the problem?

Thanks,
Damir

**Comment by hotzenklotz** [comment]
@dmedved90 I am assuming you are only referring to TTS and STT here? (Not the chat text itself, right?) 

To be honest, I haven't used those to features to much myself. Do you have any Chrome plugins that might get in the way? Other than that I am afraid I don't see any reason why Chrome should sometimes support Croatian and sometime not. :-/

Sorry that I can't be of more help here. Perhaps, you check out other web-API TTS/STT demos to see if they behavior is the same. Perhaps, then we could rule out that it is anything `chatroom` specific.

**Comment by dmedved90** [comment]
True, the only problem is TTS. It is further interesting that STT is properly recognizing Croatian and is working as expected. I will further investigate and post the solution (if found). 
Thanks for the help.

**Comment by hotzenklotz** [comment]
TTS was added by a community member to the project. Perhaps, he/she has more insights on how Chrome's TTS works. cc @diogomqbm 

Related PR: https://github.com/scalableminds/chatroom/pull/116

**Comment by diogomqbm** [comment]
Hi, @dmedved90 I tried to make a demo with "hr-HR" language but it seems to not be working as expected. In my experience, it may seem because the language isn't supported in 
`SpeechSynthesisUtterance`. However, it may not be working if your `<html> <lang>` is different, I really don't know here, I'm guessing. Check [this](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/lang). I couldn't find a proper list of supported languages.

**Comment by dmedved90** [comment]
Hi,@diogomqbm, well it seems you are right.
Using this [tool](https://jsbin.com/ginanegoqu/edit?js,output)  I confirmed that browsers don't have the same approach to detect speech languages. On the same laptop, I had three different results for Edge, Chrome, and Firefox.
I also find detailed [explanation](https://flaviocopes.com/speech-synthesis-api/) on this behavior and recommendation on how to correct this. Are you able to implement the proposed solution in the chatroom?

**Comment by diogomqbm** [comment]
Of course! I'll be working on this ASAP.

**Comment by diogomqbm** [comment]
@dmedved90 Apparently "hr-HR" is not supported on [SpeechSynthesis](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/getVoices) yet. I've added the change you've requested on https://github.com/scalableminds/chatroom/pull/125.

**Comment by hankshz** [comment]
@diogomqbm I also tried to set `voiceLang="zh-CN"` with a welcome message in Chinese, but all it says is "Chinese letter letter letter". Any idea what might be the problem? I also tried to set `lang="zh"` in the html container, but it didn't help. Thanks!

**Comment by hankshz** [comment]
Hmm, I installed the latest Chrome and it seems to work now...I was using the default Firefox in Ubuntu18.
