### ISSUE TITLE
New fetchOptions not being incorporated

### ISSUE THREAD

**Issue by OriginLeon** [scalableminds/chatroom#123]
I want to add additional headers to my request. As I looked upon your code you have:
**Object.assign({}, r.props.fetchOptions, {
                                        method: "POST",
                                        body: JSON.stringify(o),
                                        headers: {
                                            "Content-Type": "application/json"
                                        }
                                    }**
The '_fetchOptions_' parameter is assigned first to the _Object.assign_ merge function, and as such my understanding is that any headers I assign to it are replaced by yours. 
I think you could change the order for the assign, granting users the option to design their own headers for the webhooks requests.

**Comment by hotzenklotz** [comment]
Thanks for the suggestions. Feel free to provide a PR. I'd be happy to take a look and integrate it.

**Comment by OriginLeon** [comment]
@hotzenklotz i just uploaded a PR with the change. Thank you for the fast response.

**Comment by hotzenklotz** [comment]
Fixed through PR #124 

Thanks for the contribution. The changes should be available as version `0.12.0`.
