### ISSUE TITLE
Known issue that Reminders won't work?

### ISSUE THREAD

**Issue by hankshz** [scalableminds/chatroom#130]
I followed https://rasa.com/docs/rasa/core/reminders-and-external-events/ to set up a reminder. I could tell from the rasa side that the reminder event/action is triggered. But I didn't see anything updated in the chatroom UI. I guess this is the limitation of chatroom because it's using REST API (poll model only)? Did I miss anything? Maybe we should mention this limitation in the README? Thanks!

**Comment by hotzenklotz** [comment]
Good catch. I guess we never used the reminders feature. I am not even sure if the Rasa REST API exposes them somehow. 

Feel free to open a PR if you are working on a fix.

**Comment by hankshz** [comment]
I just tried webchat (https://github.com/botfront/rasa-webchat) who is using socket.io and it just worked. I guess this is something fundamentally not supported by REST model then...?
