### ISSUE TITLE
Need help to deploy this in my apache web server setup

### ISSUE THREAD

**Issue by bkhaneja** [scalableminds/chatroom#132]
I used the below index.html
<head>
  <link rel="stylesheet" href="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.css" />
</head>
<body>
  <div class="chat-container"></div>

  <script src="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.js"/></script>
  <script type="text/javascript">
    var chatroom = new window.Chatroom({
      host: "http://localhost:5005",
      title: "Chat with Mike",
      container: document.querySelector(".chat-container"),
      welcomeMessage: "Hi, I am Mike. How may I help you?",
      speechRecognition: "en-US",
      voiceLang: "en-US"
    });
    chatroom.openChat();
  </script>
</body>

my question is if i download above js script locally....it do not work and shows some missing module errors..

I am a system admin and have no knowledge of react js or node js.  

As per company policy i cannot give external links to fetch data from...  How can i use this code locally....   do i need to install anything and then build app ?

Any suggestions ..help is appreciated....

Thanks much...  its an awesome solution...

**Comment by hotzenklotz** [comment]
> As per company policy i cannot give external links to fetch data from... 

The given code sample above still fetches the Chatroom script from NPM. You should download it, reference your local version in your `index.html` and that should get you going. 
(I am not sure where you need to put the local file in Apache file structure)
