### ISSUE TITLE
How to point to docker container?

### ISSUE THREAD

**Issue by InnoOmnia** [scalableminds/chatroom#141]
I'm running rasa chatbot in docker container and exposed port 5005.  

When I run chatroom I get webpage with chat widget but no connection to rasa chatbot  
I think this is ok, because I opened that in container  
`host: "http://localhost:5005",`  
But how to use this one, should I put container name to here ".chat-container", I tried ".rasa1" and "rasa1"but no diffrence.  
`container: document.querySelector(".chat-container"),`

This is command how I start a rasa chatbot container  
`docker run --name=rasa1 --user 1002 -v $(pwd):/app -p "5005:5005" rasa/rasa:1.10.11-full run -m models --enable-api --cors "*" --debug`

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:29130         0.0.0.0:*               LISTEN      1628/mdsd
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      851/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1153/sshd
tcp6       0      0 :::5005                 :::*                    LISTEN      67278/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      1153/sshd
tcp6       0      0 :::444                  :::*                    LISTEN      68911/apache2

My environment is Azure linux server

**Comment by hotzenklotz** [comment]
I don't think this is a chatroom specific question. `host: "http://localhost:5005"` should be correct given that you can make a connect to your Rasa backend. 

`container: document.querySelector(".chat-container")` refers to the HTML container element where the widget is mounted on your page. It has nothing to do with Docker containers.

Have you tried connecting to your Rasa docker setup without the Chatroot Widget? `curl` or `postman`. Rasa should give you status response if is running correctly. E.g.
```
curl localhost:5005/webhooks/rest
>> {"status":"ok"}
```

**Comment by InnoOmnia** [comment]
This works  
curl localhost:5005/webhooks/rest
{"status":"ok"}

**Comment by hotzenklotz** [comment]
Do you have any errors reported in in your browser's dev tools? Which browser + version are you using? 

Which version of the chatroom widget and Rasa are you using?

**Comment by InnoOmnia** [comment]
Chrome Version 85.0.4183.102 
I think this is the Rasa version, from docker container command,: rasa:1.10.11
Chatroom wigdet version? I don't know, I just use that what is instructions, so this is from index.html
> <script src="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.js"/></script>

**Comment by hotzenklotz** [comment]
Mhm, versions look alright. 

Anything in the browser dev tools?

**Comment by InnoOmnia** [comment]
Sorry, forget from previous comment, here they are  
**These came when I opened page**  
Chatroom.js:1181 [Deprecation] speechSynthesis.speak() without user activation is no longer allowed since M71, around December 2018. See https://www.chromestatus.com/feature/5687444770914304 for more details
o @ Chatroom.js:1181
DevTools failed to load SourceMap: Could not load content for https://npm-scalableminds.s3.eu-central-1.amazonaws.com/Chatroom.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://npm-scalableminds.s3.eu-central-1.amazonaws.com/Chatroom.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Then these came when typed question to bot**
Chatroom.js:1197 POST http://localhost:5005/webhooks/rest/webhook net::ERR_CONNECTION_REFUSED
(anonymous) @ Chatroom.js:1197
h @ Chatroom.js:520
(anonymous) @ Chatroom.js:520
t.<computed> @ Chatroom.js:520
l @ Chatroom.js:1197
a @ Chatroom.js:1197
(anonymous) @ Chatroom.js:1197
(anonymous) @ Chatroom.js:1197
(anonymous) @ Chatroom.js:1197
(anonymous) @ Chatroom.js:1195
h @ Chatroom.js:520
(anonymous) @ Chatroom.js:520
t.<computed> @ Chatroom.js:520
a @ Chatroom.js:1195
n @ Chatroom.js:1195
(anonymous) @ Chatroom.js:1195
(anonymous) @ Chatroom.js:1195
(anonymous) @ Chatroom.js:1195
d @ Chatroom.js:536
y @ Chatroom.js:536
b @ Chatroom.js:536
x @ Chatroom.js:536
_ @ Chatroom.js:536
C @ Chatroom.js:536
P @ Chatroom.js:536
Ln @ Chatroom.js:536
Hn @ Chatroom.js:536
exports.unstable_runWithPriority @ Chatroom.js:532
bl @ Chatroom.js:536
Yo @ Chatroom.js:536
Bn @ Chatroom.js:536
Chatroom.js:1197 Uncaught (in promise) TypeError: Failed to fetch
Promise.then (async)
l @ Chatroom.js:1197
a @ Chatroom.js:1197
(anonymous) @ Chatroom.js:1197
(anonymous) @ Chatroom.js:1197
(anonymous) @ Chatroom.js:1197
(anonymous) @ Chatroom.js:1195
h @ Chatroom.js:520
(anonymous) @ Chatroom.js:520
t.<computed> @ Chatroom.js:520
a @ Chatroom.js:1195
n @ Chatroom.js:1195
(anonymous) @ Chatroom.js:1195
(anonymous) @ Chatroom.js:1195
(anonymous) @ Chatroom.js:1195
d @ Chatroom.js:536
y @ Chatroom.js:536
b @ Chatroom.js:536
x @ Chatroom.js:536
_ @ Chatroom.js:536
C @ Chatroom.js:536
P @ Chatroom.js:536
Ln @ Chatroom.js:536
Hn @ Chatroom.js:536
exports.unstable_runWithPriority @ Chatroom.js:532
bl @ Chatroom.js:536
Yo @ Chatroom.js:536
Bn @ Chatroom.js:536

**Comment by hotzenklotz** [comment]
> Chatroom.js:1197 POST http://localhost:5005/webhooks/rest/webhook net::ERR_CONNECTION_REFUSED
Well, looks like you Docker container does not accept a connection from Chrome. Hard to say from afar what is causing this.

**Comment by InnoOmnia** [comment]
ok, thanks for help
