### ISSUE TITLE
Speech recognition integration in the chatroom and bot icon beside the message

### ISSUE THREAD

**Issue by arcontechnologies** [scalableminds/chatroom#15]
Hello,
I made a little program in python that handle speech recognition and I want to integrate it to the chatroom (via speaker button).   As I'm not very familiar with react and web stack development, I wonder how I can do this without blowing up everything ?
On the other hand, how can I manage to integrate an icon beside for both user and bot messages ?

Thanks in advance for your help.

PS : I don't wanted to fork this project as I think enhancing its functionalities will be a great chatroom for Raza community. 

```
import speech_recognition as sr

def recordAudio():
    # Record Audio
    r = sr.Recognizer()    
# obtain audio from the microphone
    
    with sr.Microphone() as source:
        r.adjust_for_ambient_noise(source)
        print("Say something!")
        audio = r.listen(source)
        
 
    # Speech recognition using Google Speech Recognition
        data = ""
    try:
        # Uses the default API key
        # To use another API key: `r.recognize_google(audio, key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
        data = r.recognize_google(audio,language="en-EN")
        #data = r.recognize_sphinx(audio)
        #data = r.recognize_bing(audio)
        print("You said: " + data)
    except sr.UnknownValueError:
        print("Sorry, but, I could not understand what you said!")
    except sr.RequestError as e:
        print("Could not request results from Google Speech Recognition service; {0}".format(e))
 
    return data

if __name__ == '__main__':
    try:
        while True:
            recordAudio()
    except KeyboardInterrupt:
        exit
```

**Comment by hotzenklotz** [comment]
Hm... Adding speech recognition isn't easily done. Essentially you will need to capture / stream the audio in the browser and forward it to the chat backend / sever which sends it to Google / Bing etc. This is quite involved. 

Perhaps take a look at the WebSpeech API which will let you do speech recognition in the browser saving you from all the hassle with the server. It is still very experimental and might not be supported by all browsers etc. 
https://developers.google.com/web/updates/2013/01/Voice-Driven-Web-Apps-Introduction-to-the-Web-Speech-API

**Comment by arcontechnologies** [comment]
thanks for your reply. I'll investigate this.
