### ISSUE TITLE
Change text language for welcome text

### ISSUE THREAD

**Issue by ratneshjoshi** [scalableminds/chatroom#152]
var chatroom = new window.Chatroom({
        host: "http://172.16.26.60:5006",
        title: "Hindi bot",
        container: document.querySelector(".chat-container"),
        // speechRecognition: "en-US",
        // voiceLang: "en-US",
        welcomeMessage: "Hi, I am Botty. Get started by saying नमस्कार."
      });

In the welcome message if I type the message in non English language it doesn't work(shows unprocessed characters for Hindi text in my case) which parameter to set to allow other languages for text? When the bot connects, it is able to work in other languages as well, just the welcome message fails.

**Comment by hotzenklotz** [comment]
I am not sure how to help you. If would have expected the browser the handle UTF8 just right. Do you have a UTF8 header in your HTML page? See https://www.w3schools.com/tags/att_meta_charset.asp

**Comment by ratneshjoshi** [comment]
Hadn't set that. That took care of it. Thanks.
