### ISSUE TITLE
Unable to receive message from the slack app

### ISSUE THREAD

**Issue by Manoj1229** [scalableminds/chatroom#154]
I am unable to receive the message from the slack app to the chat room application. But, slack is able to receive from the chat app.

**Comment by hotzenklotz** [comment]
The chatroom is a web online connector for putting a Rasa bot on your website. It is independent of other channels such as Slack, FB Messenger etc and does not interact with them. (This is also not intended by Rasa). 

You can NOT interact between Slack and this Chatroom widget. There is no session forwarding between the two.
