### ISSUE TITLE
Minimal example for how to use this with rasa?

### ISSUE THREAD

**Issue by tide90** [scalableminds/chatroom#157]
Hey 2 years ago it was very intuitive to use this with rasa. But I cannot find any instructions along an examples? 

Does any one know whre I can find infos or an examples where I can start a server like before via python (without any advanced stuff) and use this with this ui? The rasa docs are not helpful.

**Comment by hotzenklotz** [comment]
Is the README not enough? https://github.com/scalableminds/chatroom#usage

**Comment by tide90** [comment]
Thanks. I struggle with this:

> Depending on your setup you might need to start the Rasa CLI / Rasa server with the right CORS

So is there some example? Is meant with rasa server the same as rasa action server?

**Comment by hotzenklotz** [comment]
You just need to restart your rasa server with `rasa run`.

Something like:
```
rasa run --credentials credentials.yml  --enable-api --auth-token XYZ123 --model ./models --endpoints endpoints.yml --cors "*"
```
