### ISSUE TITLE
Hosted CSS - Is it correct?

### ISSUE THREAD

**Issue by pomegran** [scalableminds/chatroom#161]
Hi,

I am quickly using your interface to test voice but the UI looks like the CSS isn't working (compared to your images).  I am using your template code on the GitHub page and it looks like the attached image in Chrome.

It doesn't look as nice as yours - is this correct or an error in the template?

Thank you!

![chatbotui](https://user-images.githubusercontent.com/13970301/114389822-65782a00-9b8d-11eb-8aac-849bcdc6697f.png)

**Comment by hotzenklotz** [comment]
This is working as intended. Make sure to wrap the Chatroom component in a `<div>` and position/resize this as needed.

**Comment by pomegran** [comment]
Thanks for the quick response Tom.  Will look into that right now.
