### ISSUE TITLE
Customize css

### ISSUE THREAD

**Issue by ctrado18** [scalableminds/chatroom#19]
Changes in charoom.scss does not change anything. I tried to change text color. But nothing happened. I did yarn build afterwards.

I am completely new to css and html.
I just want to remove the transparency from the text window. You can see the background from the wepage...and maybe change the postion of the container

**Comment by normanrz** [comment]
You can change the background color here: https://github.com/scalableminds/chatroom/blob/master/src/Chatroom.scss#L1
If you want no transparency, make sure the use `1` as the last component, e.g. `$backgroundColor: rgba(200, 200, 200, 1);`

After making a change, you need to run `yarn build` again.
