### ISSUE TITLE
Embedding on Wordpress

### ISSUE THREAD

**Issue by btotharye** [scalableminds/chatroom#20]
So I have your widget working at https://rasa.btotharye.com but is there a easy way you know of to embedd this on my wordpress site without having to use iframes?

**Comment by btotharye** [comment]
for what it's worth for now I'm using iframes and you can see it in action at https://geekedoutsolutions.com/mycroft-chatbot

**Comment by btotharye** [comment]
Sounds good was just checking.  I’m working on a better way in Wordpress to have the chatbot show up at the bottom right of the pages

**Comment by normanrz** [comment]
In our pages we just include the JS and CSS files directly in our website (view-source:https://scalableminds.com/). This approach may lead to conflicts with your CSS though. Iframe encapsulate better.
