### ISSUE TITLE
Issue while using yarn install

### ISSUE THREAD

**Issue by AnilLG** [scalableminds/chatroom#22]
Hi there,

I am trying to install this yarn repository  and while executing the command `yarn install` I get Unexpected token error in index.js as following.
![screenshot from 2018-07-12 14-46-54](https://user-images.githubusercontent.com/39720422/42624224-821b482c-85e2-11e8-9a31-97b8711fde93.png)

My sytem configuration is as follows:
Ubuntu 18.04
Node 10.6
yarn 1.7

**Comment by palash247** [comment]
It seems you love using everything **new** as it comes to the market, with Node 10.6, I will say, **new**, which is not stable. Try installing the stable version of Node instead of most recent. :)

**Comment by AnilLG** [comment]
Thank you palash :) :)

**Comment by Brijeshlakkad** [comment]
I am having same error and i have  node v10.9.0 and yarn v1.9.4. Please help me

**Comment by normanrz** [comment]
@Brijeshlakkad what commands did you use?

**Comment by Brijeshlakkad** [comment]
$ yarn install

**Comment by normanrz** [comment]
I pushed a dependency upgrade. Can you pull and try again?

**Comment by Brijeshlakkad** [comment]
Still showing that error :(
