### ISSUE TITLE
Store intent and entities

### ISSUE THREAD

**Issue by ctrado18** [scalableminds/chatroom#25]
Hi,

how would I change the https://github.com/scalableminds/chatroom/blob/master/rasa_utils/bot_server_channel.py

to store also entities and intents from Rasa NLU?

**Comment by hotzenklotz** [comment]
I am not sure what you are trying to do here? Please explain in more detail.

In general, the `bot_server_channel` just provides a way to input / output text to Rasa NLU., just like the command line interface channel or FB messenger channel. Entities and intents are internal constructs of NLU. 

If you wish to output the discovered intents / entities either check the log files of your bots or include them in the bot's answers (e.g. custom action).

**Comment by ctrado18** [comment]
I would like to store in the `message_Store` file the intents and entities from NLU, like the message text and user Id are saved right now. So could you access the NLU informations from there?

**Comment by ctrado18** [comment]
I guess I can just extract the data using like `tracker.latest_message.parse_data["intent"]["name"]` in the above file and store it in the MessageStore together with the other data?

**Comment by ctrado18** [comment]
Just a short answer would be nice. 😄

**Comment by hotzenklotz** [comment]
I am sorry. I still don't understand the question but it looks like you already found an answer. This chatroom is a simple adapter between our custom web component and Rasa Core. This is just another custom channel similar to the FB Messenger or Slack integration for Core.

Checkout the channels documentation to see what APIs are available: http://rasa.com/docs/core/connectors/#custom-channels

**Comment by normanrz** [comment]
I believe #27 is similar to your request.
