### ISSUE TITLE
chatroom connection to dockered bot

### ISSUE THREAD

**Issue by ctrado18** [scalableminds/chatroom#31]
Hey,

i dockered my bot which starts the Klein server at port 5002. Forwarding the port works and I can access the server with docker toolbox IP `http://192.168.99.100:5002/health` successfully. But the GUI at `http://127.0.0.1:8080/` seems not be connected with the bot although I gave the host inside index.html to be `192.168.99.100:5002`

What I have to do so the chatrrom can communicate with the docker bot?

**Comment by normanrz** [comment]
Are there any errors in the JS dev console?
