### ISSUE TITLE
[Question] Trouble connecting to a custom backend

### ISSUE THREAD

**Issue by smasschelin** [scalableminds/chatroom#34]
Hello,

So I have a custom Rasa backend/server that I'm using. The data is being passed in the form of a JSON, and the query takes the form of `localhost:(PORT)/parse?q=`. I've noticed that when I try to connect via the chatroom, that query takes the form of `localhost:(PORT)/conversations`. Is there a way to change the way that chatroom's queries are formed? The bot is pointing towards the correct port that my data would streaming in on. Secondly, is there also a way to turn off the once-per-second logging of the errors? I've attached a screenshot below

<img width="1632" alt="screen shot 2018-09-07 at 14 05 02" src="https://user-images.githubusercontent.com/31043761/45235557-35ff3380-b2a7-11e8-86ba-cef4cf9525e8.png">

Thank you once again

**Comment by normanrz** [comment]
Hi, seems like you're connecting the chatroom directly to Rasa NLU. The Chatroom needs to connect to a REST-API that is implemented in https://github.com/scalableminds/chatroom/blob/master/rasa_utils/bot_server_channel.py

**Comment by smasschelin** [comment]
Ah. Thank you. I'll close this out then.
