### ISSUE TITLE
Chatroom not working from non-local environment with RASA bot backend

### ISSUE THREAD

**Issue by darkblueorange** [scalableminds/chatroom#35]
Hello, 
First of all, thank you for all the good work and all the nice stuff you propose!
I'm trying to plug a front to my RASA bot with your code. 
I succeed in getting the chatroom working with RASA core in back from : 
 - 127.0.0.1:8080
 - 192.168.x.x:8080 (any local address given by my DHCP)
 - blabla.ngrok.io 
and getting answers from my RASA bot configured, but always locally => from my laptop (where all the stuff is installed). 

From any external devices, I get the first page, with welcome message, can see user messages posted but no answers coming back from the bot. 
Actually I have the feeling that the backend does not receive any message when I use an external device. 
I tried from Mozilla, IE, iPhone nav, etc
As I get the first page, I don't believe it could be any NAT or firewall issue, but I don't get from where it is blocking ...
I'm not familiar with React or any front unfortunately ... so I'm struggling into modifying any line of codes to debug anything. 
Many thanks for your help.

**Comment by normanrz** [comment]
Have you changed the `host` parameter as in https://github.com/scalableminds/chatroom/blob/master/index.html#L18?

**Comment by darkblueorange** [comment]
Thank you for your quick reply.
I am not sure :
 - the host parameter is designed to dialogue with bot_server_channel.py right ?
 - I did put both on localhost port 10001

**Comment by normanrz** [comment]
The `host` parameter is what the Browser will use to contact the BotServerChannel. If the BotServerChannel runs on a remote host, e.g. blabla.ngrok.io:10001, you will need to set the `host` to that.

**Comment by darkblueorange** [comment]
Ok so I finally got it work : 
1- launching "ngrok http 8080" to cast the basic local yarn web server on -for eg- "blabla.ngrok.io" for the outside
2- launching "ngrok http 5002" (if default port conf, or 10001 in my case) to cast the BotServerChannel on -for eg- "toto.ngrok.io" for the outside
3- modification of the index.html with "toto.ngrok.io" instead of "localhost:5002"

4- launching BotServerChannel & yarn serve (after yarn build & install)
5- accessing blabla.ngrok.io from my outside computer, and then ... getting the bot working finally, yay ! :-)

Thanks again for your work

**Comment by hotzenklotz** [comment]
Nice. Thanks for sharing the solution.

**Comment by PravinrajV** [comment]
I have installed and followed the instructions.
I have 3 terminals running --> Yarn serve, actions, bot.
When I type in the chatroom, I see that in the Bot terminal, but i dont get any response displayed in the Chatroom.
I am using default host: "http://localhost:5002".
I am not getting any response in my chatroom.

![04_ui_capture](https://user-images.githubusercontent.com/31581909/45912922-9e95f680-bdf7-11e8-9af7-c0a2060e01ac.PNG)
![03_bot_capture](https://user-images.githubusercontent.com/31581909/45912923-9e95f680-bdf7-11e8-9524-e63b4f6333e8.PNG)
![02_actions_capture](https://user-images.githubusercontent.com/31581909/45912924-9e95f680-bdf7-11e8-8ba4-b2a909a6d295.PNG)
![01_yarn_capture](https://user-images.githubusercontent.com/31581909/45912925-9e95f680-bdf7-11e8-85e6-e940198b239e.PNG)

**Comment by PravinrajV** [comment]
I checked the browser --> dev tools --> network tab and can see the below in the response:

<title>404 Not Found</title>
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
