### ISSUE TITLE
Error while adding InputChanel to Agent

### ISSUE THREAD

**Issue by dbhadore** [scalableminds/chatroom#39]
I'm getting following error while trying to add chanel to rasa_core.agent

agent.handle_channel(channel)
AttributeError: 'Agent' object has no attribute 'handle_channel'

If tried changing it to - agent.handle_channels(channel)
TypeError: 'BotServerInputChannel' object is not iterable

# Code:
from bot_server_channel import BotServerInputChannel
from rasa_core.agent import Agent
from rasa_core.interpreter import RasaNLUInterpreter

def main_server():
    agent = Agent.load("models/dialogue",RasaNLUInterpreter("models/current/nlu"))
    channel = BotServerInputChannel(agent)
    agent.handle_channels(channel)

main_server()

Looks like there is no function called handle_channel in rasa_core.agent. Not sure how the code is working for all.

**Comment by normanrz** [comment]
Seems like Rasa Core's API has changed. Could you try `agent.handle_channels([channel])`?

**Comment by dbhadore** [comment]
Yes. tried that.
Now getting kages\rasa_core\channels\channel.py", line 90, in blueprint
    "Component listener needs to provide blueprint.")
NotImplementedError: Component listener needs to provide blueprint.

**Comment by dbhadore** [comment]
Is this also happening due to change in version? Is there a quick fix for this?

**Comment by quarksys** [comment]
which version of rasa_nlu that I should use?

**Comment by darkblueorange** [comment]
Latest version of rasa_nlu (0.13.2 for me) can work, indeed for rasa_core you cannot go over 0.10.4 as handle_channel() does not exist anymore with the actual release.

**Comment by hotzenklotz** [comment]
Rasa has changed their Core APIs quite significantly for input channels. We will update the chatroom to use the new Rasa Core SDK within the next two weeks.

**Comment by nicolepilsworth** [comment]
I've written a fix for this that works with `rasa_core` 0.11.5. It involves some changes in `bot.py` and `bot_server_channel.py`. I could open a pull request for this if it's easier?

**Comment by PravinrajV** [comment]
> I've written a fix for this that works with `rasa_core` 0.11.5. It involves some changes in `bot.py` and `bot_server_channel.py`. I could open a pull request for this if it's easier?

I am facing the same issue.
Would you please post the fix here .

**Comment by hotzenklotz** [comment]
@nicolepilsworth Feel free to open a PR. We will take a look :-)

Did you upgrade the bot integration to use the new [REST channel](https://rasa.com/docs/core/connectors/#rest-channels)?

**Comment by nicolepilsworth** [comment]
I changed the existing code in `BotServerInputChannel` to use the new [Flask blueprint](https://rasa.com/docs/core/connectors/#creating-a-new-channel) code.

Here's my PR: https://github.com/scalableminds/chatroom/pull/43

**Comment by PravinrajV** [comment]
@nicolepilsworth I get the below error when I type in the chatroom:


```
09-25 09:16:00] "GET /webhooks/chatroom/conversations/0fd18a6d-e802-47c1-a24c-75
he=1537881360245 HTTP/1.1" 200 183 0.000977
INFO     root  - []
ERROR    flask.app  - Exception on /webhooks/chatroom/conversations/0fd18a6d-e80
59e1/say [GET]
nt call last):
iles\Python35\lib\site-packages\flask\app.py", line 2292, in wsgi_app
full_dispatch_request()
iles\Python35\lib\site-packages\flask\app.py", line 1815, in full_dispatch_reque

_user_exception(e)
iles\Python35\lib\site-packages\flask\app.py", line 1718, in handle_user_excepti

, exc_value, tb)
iles\Python35\lib\site-packages\flask\_compat.py", line 35, in reraise

iles\Python35\lib\site-packages\flask\app.py", line 1813, in full_dispatch_reque

ch_request()
iles\Python35\lib\site-packages\flask\app.py", line 1799, in dispatch_request
_functions[rule.endpoint](**req.view_args)
atbot\Uibot\rasa_utils\bot_server_channel.py", line 182, in say
age(
ServerInputChannel' object has no attribute 'on_new_message'

```

**Comment by PravinrajV** [comment]
This working fine now.
Thank you very much @nicolepilsworth

**Comment by abhishakvarshney** [comment]
I got the below error:
**Traceback (most recent call last):
  File "test.py", line 39, in <module>
    main_server()
  File "test.py", line 37, in main_server
    agent.handle_channels(channel)
  File "/usr/local/lib/python3.6/dist-packages/rasa_core/agent.py", line 528, in handle_channels
    route="/webhooks/")
  File "/usr/local/lib/python3.6/dist-packages/rasa_core/channels/channel.py", line 58, in register
    for channel in input_channels:
TypeError: 'BotServerInputChannel' object is not iterable**

**Comment by hotzenklotz** [comment]
PR #43 has been merged so I am closing this issues. The chatroom should now be compatible with Rasa Core `0.11.5+`.
