### ISSUE TITLE
Forum to ask questions besides issues related to this UI

### ISSUE THREAD

**Issue by r4sn4** [scalableminds/chatroom#41]
Is there any forum to ask questions ?

**Comment by normanrz** [comment]
Not yet, but good idea!

**Comment by PravinrajV** [comment]
Hi,
I am new to this. Need help getting started.
I have created a small bot with custom actions.
It is working fine in the command line.

Now, I am trying to use this chatroom.

1. In terminal 1: I have the http server running:

```
yarn run v1.9.4
$ http-server
Starting up http-server, serving ./
Available on: http://127.0.0.1:8080/
```
2. In terminal 2, I have
python -m rasa_core_sdk.endpoint --actions actions

INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)

3. In terminal 3, 
python bot.py -d models/current/dialogue -u models/current/nlu -p 5002
running fine.

The chat room is not loading in "http://localhost:5002/".but it is loading in the 8080 port.

When i type a text,  I am able to see the message in terminal 3:

127.0.0.1 - - [2018-09-21 20:32:44] "GET /conversations/f50a6bb4-e8a9-4ea0-abe3-
sage=helo&uuid=1d63bfd6-44da-4137-a3a3-646d9fa78e32 HTTP/1.1" 404 342 0.000977

But no response in the chat room.
In terminal 1, i see 

[Fri Sep 21 2018 20:32:19 GMT-0400 (Eastern Daylight Time)] "GET /favicon.ico" Error (404): "Not fou
nd"


Please help.

**Comment by PravinrajV** [comment]
I checked the browser --> dev tools --> network tab and can see the below in the response:

<title>404 Not Found</title>
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by hotzenklotz** [comment]
Rasa has a community forum now. Check it out: https://forum.rasa.com
