### ISSUE TITLE
Add audio type in bot response

### ISSUE THREAD

**Issue by r4sn4** [scalableminds/chatroom#44]
Hi

I have use case where person can interact with bot using audio. 
When user says something using audio, it gets converted to text first. Then, This text is sent to bot endpoint and text response is returned. I want to add one field in this response that this text response had type audio so that at UI end, it can be resolved as required.

**Comment by hotzenklotz** [comment]
That should be possible. Just fork the project and add the new field to the response in the custom Rasa channel (Python) and use that information in the web frontend (Javascript) to display an icon etc.

**Comment by r4sn4** [comment]
In which file do i need to make changes?

**Comment by hotzenklotz** [comment]
The Chatroom now support speech input and text synthesis (PR #116 ).
