### ISSUE TITLE
TypeError: 'BotServerInputChannel' object is not iterable

### ISSUE THREAD

**Issue by abhishakvarshney** [scalableminds/chatroom#47]
When I run the code below:

```
from bot_server_channel import BotServerInputChannel
##Creating the Interpreter and Agent
def load_agent():
    action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")
    interpreter = RasaNLUInterpreter("./models/default/nlu")
    tracker_store = MongoTrackerStore(domain ="domain.yml", host="http://localhost:27017",db="test",username="username",password="password",collection="conversations")
    agent = Agent.load("./models/dialogue",interpreter=interpreter,action_endpoint=action_endpoint,tracker_store = tracker_store)
    return agent
##Creating the server
def main_server():
    agent = load_agent()
    channel = BotServerInputChannel(agent)
    agent.handle_channels(channel)

main_server()
```

I got the below error:

**In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
Traceback (most recent call last):
  File "test.py", line 39, in <module>
    main_server()
  File "test.py", line 37, in main_server
    agent.handle_channels(channel)
  File "/usr/local/lib/python3.6/dist-packages/rasa_core/agent.py", line 528, in handle_channels
    route="/webhooks/")
  File "/usr/local/lib/python3.6/dist-packages/rasa_core/channels/channel.py", line 58, in register
    for channel in input_channels:
TypeError: 'BotServerInputChannel' object is not iterable**
 
Can you help me how can I resolve this issue/

**Comment by hotzenklotz** [comment]
I think `agent.handle_channels(channel)` expects an array of channels. Try `agent.handle_channels([channel])`

I updated the README, accordingly.
