### ISSUE TITLE
Issues connecting Rasa to chatroom bot

### ISSUE THREAD

**Issue by asaiyed10** [scalableminds/chatroom#48]
1. Create a credentials file, e.g. `channel_credentials.yml` with the fully qualified path to the Python class, e.g.:
```
bot.helpers.chatroom_channel.BotServerInputChannel:
  # pass
```
2. Start the Rasa bot using the commandline and pass the `--credentials`flag:
``` 
	python -m rasa_core.run  \
		--core models/current/dialogue  \
		--nlu models/current/nlu  \
		--endpoints endpoints.yml \
		--credentials channel_credentials.yml
```

_Originally posted by @hotzenklotz in https://github.com/scalableminds/chatroom/pull/43#issuecomment-425838055_

So I still keep getting 404 errors despite following the steps above. 

<img width="1157" alt="screen shot 2018-10-09 at 3 49 15 pm" src="https://user-images.githubusercontent.com/22109013/46694472-f5167980-cbda-11e8-993f-dd7d0d2aa9f5.png">

I'm sure the problem is on my end so if anyone could help troubleshoot, I would be very grateful. 

Rasa_core= 11.1

The path to the python class BotServerInputChannel, is from bot_server_channel.py recently edited and pushed to this repo/from the approved pull request, correct? Its not the deafult version that comes with rasa_utils. 

Also, are we supposed to specificy anything in the endpoints.yml file besides the action and core server?

**Comment by hotzenklotz** [comment]
@asaiyed10 Let's see what's going on here. 

To make sure that the custom channel is loaded and working run the above command with verbose options (`-vv`). E.g. `python -m rasa_core.run -vv ...`

The output should include an overview like this:
```
2018-10-10 12:02:59 DEBUG    rasa_core.utils  - Available web server routes:
static                                             HEAD, GET, OPTIONS             /static/[filename]
bot_server_webhook.static                          HEAD, GET, OPTIONS             /webhooks/chatroom/
bot_server_webhook.show_log                        HEAD, GET, OPTIONS             /webhooks/chatroom/conversations/[cid]/log
bot_server_webhook.say                             HEAD, GET, OPTIONS             /webhooks/chatroom/conversations/[cid]/say
bot_server_webhook.tracker                         HEAD, GET, OPTIONS             /webhooks/chatroom/conversations/[cid]/tracker
bot_server_webhook.health                          HEAD, GET, OPTIONS             /webhooks/chatroom/health
bot_server_webhook.receive                         POST, OPTIONS                  /webhooks/chatroom/webhook```

**Comment by asaiyed10** [comment]
<img width="965" alt="screen shot 2018-10-10 at 1 15 44 pm" src="https://user-images.githubusercontent.com/22109013/46753774-b80bbf00-cc8e-11e8-8ca5-45f5c1a53ceb.png">

**Comment by asaiyed10** [comment]
So I have health and receive, but they are "custom_webhooks", instead of  "bot_server_webhooks". So this is a credentials file issue, right?

**Comment by hotzenklotz** [comment]
Yes, it looks like the custom channel wasn't initialised. Double check that the Python class path on the `credentials.yml` is correct. It has to point to the location and class of the custom channel file `bot_server_channel.py`.

```
<path/to/the/file>/bot_server_channel.BotServerInputChannel:
# pass
```

**Comment by asaiyed10** [comment]
Thank you for your help!

**Comment by abarthakur** [comment]
Hi @asaiyed10 I am facing the same issue. How did you solve it? Was the path incorrect?

**Comment by GraphGrailAi** [comment]
I have the same issue, how to solve?
