### ISSUE TITLE
Providing CORS

### ISSUE THREAD

**Issue by abhishakvarshney** [scalableminds/chatroom#49]
Hi, I am using your service which is pretty good but I am unable to provide cors in web service. I know that there is cors option in bot server channel but I think it's for rasa_core and it is not helping me to whitelist my url on another server or PC, where I was running my bot.

**Comment by hotzenklotz** [comment]
I am not quite sure I understand the problem.

The custom channel should be CORS enabled already:
https://github.com/scalableminds/chatroom/blob/master/rasa_utils/bot_server_channel.py#L104

As far as I can tell the bot responses already have the CORS headers present: 
![image](https://user-images.githubusercontent.com/1105056/46736732-0d010280-cc9a-11e8-8379-f5a3cb624651.png)

**Comment by abhishakvarshney** [comment]
Yeah I know that but after using that I am unable to chat with bot from another PC. However, I am able to chat with bot on the same PC.

**Comment by hotzenklotz** [comment]
This is most likely not a CORS issues. Sounds like you configured the web frontend to connect to the `host` : `localhost`? Most likely you want this to be the public IP address / domain of the computer where your bot is hosted. Then you should be able to connect to the bot from another computer.

```
    var chatroom = window.Chatroom({
      host: "http://localhost:5005",
      container: document.querySelector(".chat-container"),
    });
```

**Comment by abhishakvarshney** [comment]
Yeah, I know that and I am not using local address. I am using public url using ngrok tunneling.

**Comment by abhishakvarshney** [comment]
Resolved!!! I was missing yarn build after changing the URL in index.html. I directly ran yarn serve command after changing the URL.
