### ISSUE TITLE
Error while accessing chatroom outside installed server

### ISSUE THREAD

**Issue by ATS-Official** [scalableminds/chatroom#52]
When i try to launch Chatroom from in the network using IP or DNS doesnt work, it works only on localhost, could you please help for any configuration change to launch chatroom launched within a network

var chatroom = window.Chatroom({
      host: "http://**DNSORIP**:5005",
      title: "Chat with Mike",
      container: document.querySelector(".chat-container"),
      welcomeMessage: "Hi, I am Mike. How may I help you?"
    });

**Comment by hotzenklotz** [comment]
We have the chatbot running in various complicated (internal) networks and on the internet without any issues. This is most likely a configuration issue on your side (firewall, port forwarding, DNS resolving etc).
