### ISSUE TITLE
Launch GUI at another port than 8080

### ISSUE THREAD

**Issue by ctrado18** [scalableminds/chatroom#55]
Hi,

how could you change the default port of 8080?

**Comment by hotzenklotz** [comment]
Launch a web server that serves the JS / HTML / index.html and configure it to another port. 

`yarn server` is just a connivence features for developers and shouldn't be used for production.

**Comment by ctrado18** [comment]
@hotzenklotz 

Thanks. Can you recommend something to do that? Is it possible ti use node http-server to just handover the foder like written here: https://stackabuse.com/how-to-start-a-node-server-examples-with-the-most-popular-frameworks/ ?

**Comment by hotzenklotz** [comment]
You can use just about any HTTP server, e.g. Apache, Nginx etc. A node server like above should work as well. After all, the web channel is just a website.

**Comment by ctrado18** [comment]
Do I have to build like with yarn before using node server? Can I build it with yarn and stat it with node?

I wonder why I cant give a port in the package.json?
