### ISSUE TITLE
Custom Action is not being called from chatroom webhook

### ISSUE THREAD

**Issue by Brijeshlakkad** [scalableminds/chatroom#56]
I m using rasa_core 0.11.12
and using
1. $ python -m rasa_core_sdk.endpoint --actions actions (To run custom actions)
2. $ yarn serve
3. $ python -m rasa_utils.bot  -d models/dialogue -u models/nlu/default/bank_nlu
but i can not get any responses at frontend.
```
<html>
<head>
  <link rel="stylesheet" href="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.css" />
</head>
<body>
  <div class="chat-container"></div>

  <script src="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.js"/></script>
  <script type="text/javascript">
    var chatroom = window.Chatroom({
      host: "http://localhost:5005",
      title: "Chat with Mike",
      container: document.querySelector(".chat-container"),
      welcomeMessage: "Hi, I am Mike. How may I help you?"
    });
    chatroom.openChat();
  </script>
</body>
</html>
```

**Comment by hotzenklotz** [comment]
Hi. That is very little information to help you with.

1. Make sure that your actions are working properly with another channel. (e.g. command line or Slack etc)
2. Check the command line output for errors
3. Check your Browser's Dev Tools for the network traffic
4. Try manually sending a REST call to to the channel to check if it is working correctly. Send a `GET`request to `<host:port>/webhooks/chatroom/conversations/<user_id>/say?message=hi` and check the response.

**Comment by hotzenklotz** [comment]
Custom actions are executed through Rasa Core not directly through our Chatroom.

The data flow should be as follows:
1. User input from chatroom
2. Data is received by Rasa Core 
3. Intent Classification is trigger by Rasa Core (typically using Rasa NLU)
4. Next bot (re)action is predicted by Rasa Core
5. Action is executed
6. Result of an action is send back to user and displayed in chatroom. 

Therefore, I would assume that if a custom action is triggered all the previous steps must have been successful as well. Hence, the chatroom integration with Rasa Core must have been successful.

**Comment by dipenpatel235** [comment]
6. Result of an action is send back to user and displayed in chatroom.

last action is not working only,other all actions are successfully run,
is it anything else need to change in chatroom code ?
as because custom action is run on another port how to get result back to the chatroom,

as because of i run same rasa bot code custom action is also working well.
thanks
