### ISSUE TITLE
NameError: name 'cmdline_args' is not defined

### ISSUE THREAD

**Issue by vishnudatsci** [scalableminds/chatroom#59]
I am trying to add the [https://github.com/JustinaPetr/Weatherbot_Tutorial](https://github.com/JustinaPetr/Weatherbot_Tutorial) 'WEATHER BOT' to a website. (Or sample HTML) page. I used the steps given in **Advanced Usage with a custom Rasa Core project as Custom Channel from Python**.

Following is the code I ran ('run_application.py') after executing the previous steps suggested in the page (i.e. Steps under **Basic Usage** - Running build and HTML page for your Chatroom)

```
import os
from rasa_core.channels import HttpInputChannel
from rasa_core.agent import Agent
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_slack_connector import SlackInput
from bot_server_channel import BotServerInputChannel

# Creating the Interpreter and Agent
def load_agent(): 
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/productnlu')
    agent = Agent.load('./models/dialogue', interpreter = nlu_interpreter)

# Creating the server
def main_server():
    agent = load_agent()

    channel = BotServerInputChannel(agent, port=cmdline_args.port)
    agent.handle_channels([channel], http_port=cmdline_args.port)

main_server()
```
Got the following error:

```
Traceback (most recent call last):
  File "run_application.py", line 26, in <module>
    main_server()
  File "run_application.py", line 23, in main_server
    channel = BotServerInputChannel(agent, port=cmdline_args.port)
NameError: name 'cmdline_args' is not defined
```

**Comment by hotzenklotz** [comment]
Thanks for bringing this to our attention. I simply copied our [example code](https://github.com/scalableminds/chatroom/blob/master/rasa_utils/bot.py#L129 tin) to the readme. In your case, you can just use any port. The default is `5005`. 

I will fix the readme accordingly.

**Comment by vishnudatsci** [comment]
@hotzenklotz  Leaving a comment for a different issue as it occurred in the same code line after changing the port number as suggested. 

Got error @ **agent.handle_channels([channel], http_port=cmdline_args.port)**

```
Traceback (most recent call last):
  File "run_application.py", line 23, in <module>
    main_server()
  File "run_application.py", line 21, in main_server
    agent.handle_channels([channel], http_port=5005)
AttributeError: 'NoneType' object has no attribute 'handle_channels'
```

**Comment by hotzenklotz** [comment]
@vishnudatsci Looks like `agent` is undefined. In the code above, the `load_agent` function does not return the agent.

**Comment by vishnudatsci** [comment]
@hotzenklotz Before creating a custom channel using **chatroom**, I tried the bot using slack with the following code. For the current code, the only change is creating the server. I'm not sure what is wrong.
```

from rasa_core.channels import HttpInputChannel
from rasa_core.agent import Agent
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_slack_connector import SlackInput


nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/productnlu')
agent = Agent.load('./models/dialogue', interpreter = nlu_interpreter)

input_channel = SlackInput(
        #Access keys
        #Access Tokens,
        True)

agent.handle_channel(HttpInputChannel(5004, '/', input_channel))
```

**Comment by hotzenklotz** [comment]
From your code bit, I can already tell that you are using examples for different version of Rasa core.
`agent.handle_channel(channel1)` has been changed to `agent.handle_channels([channel1, channel2, ...])` in recent version. Make sure to use Rasa Core `0.11.x`.

**Comment by vishnudatsci** [comment]
@hotzenklotz Okay, Thanks.  My RASA core version is 0.10.4. I guess I would have to update to make this work :/
