### ISSUE TITLE
log?nocache ?

### ISSUE THREAD

**Issue by ctrado18** [scalableminds/chatroom#61]
Hey,

is it possible that latest master is no more working with rasa core version 10.4?

I get correctly the message from the GUI like: `webhooks/chatroom/conversations/id/say?message=hi`

but afterwards I just get messages like : `webhooks/chatroom/conversations/id/log?nocache=10102203`

I setted up it on a virtual machine, both gui and python web server are working separately.

**Comment by normanrz** [comment]
Yes, the latest version requires `rasa_core` version 0.11
