### ISSUE TITLE
User messages are stacked below bot messages?

### ISSUE THREAD

**Issue by ctrado18** [scalableminds/chatroom#62]
I acces the gui via VPN on a virtual machine. Then I recognize that the user messages are stacked below the bot messages. Testing it locally or directly on the VM works normally.

Like.

bot: bla
bot: bla2
bot: bla3
user: hi
user: need help
user: ok

after each user input his messages are stacked below and the bot messages come before the first user message!

version: 0.7.3

**Comment by hotzenklotz** [comment]
I don't think this is something that we can help you with remotely. Please try to debug the issue on your end / with your setup / your VPN. We are happy to accept a Pull Request with fixes.
