### ISSUE TITLE
Until which version before Rasa 0.11?

### ISSUE THREAD

**Issue by ctrado18** [scalableminds/chatroom#63]
Which version works without rasa 0.11? I saw in commits that also a debug view is now iplemented? Can I use this (which version?) without rasa 0.11? And if not can you offer the same for rasa version below 0.11?

**Comment by hotzenklotz** [comment]
I updated the Readme to include a list of compatible versions. Checkout 183b38e326179e77729d746712530132ccb36096 .

I believe Chatroom version `0.7.x` should work with Rasa Core `0.10.4+`.

**Comment by hotzenklotz** [comment]
To use the debug view open `debug.html`. (https://github.com/scalableminds/chatroom/blob/master/debug.html)  

Your bot must be connected using the Python interface and needs access to the `agent. See https://github.com/scalableminds/chatroom#advanced-usage-with-a-custom-rasa-core-project-as-custom-channel-from-python
