### ISSUE TITLE
Deactivate the button after user selects it

### ISSUE THREAD

**Issue by Rajskc** [scalableminds/chatroom#64]
How can we deactivate the buttons once users clicks on it and moves to next question?

**Comment by jstriebel** [comment]
If I understand this correctly, you want to prevent users from clicking multiple times on a butten (e.g. double-clicking). Is this correct?

**Comment by AbrarAhmedQuresh** [comment]
abrarahmed@abrarahmed-HP-Notebook:~/sql_troubleshooting$ python3 dialogue_management_model.py 
Traceback (most recent call last):
  File "dialogue_management_model.py", line 19, in <module>
    from bot_server_channel import BotServerInputChannel
ModuleNotFoundError: No module named 'bot_server_channel'

I have updated to the latest version of rasa_core. help me out, please 

Thanks in advance
