### ISSUE TITLE
0.8.x releases missing as usable sources on AWS

### ISSUE THREAD

**Issue by StefanKock** [scalableminds/chatroom#67]
Hello,

I'm trying to get _chatroom_ running for a demo with Rasa Core 0.11.x.

The _Usage_ example refers to https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds for compiled CSS and JS, but it seems the 0.8.x versions are missing and master seems to be a 0.7.x release.

Would you be so kind and provide also the 0.8.2 release?

Thx, Stefan

**Comment by normanrz** [comment]
Thanks for bringing this to our attention. There was an issue with our CI. All versions ≥0.8.0 should be published to S3 now.

**Comment by StefanKock** [comment]
Yes, it's there. Thx for the quick fix
