### ISSUE TITLE
Run server in background

### ISSUE THREAD

**Issue by neerajb1** [scalableminds/chatroom#69]
Hi All ,

I am very new to node. I am using this app for rasa bot. How i can run it in background. Currently i am running as yarn serve but when i am closing terminal app also stopping.

**Comment by hotzenklotz** [comment]
`yarn serve` is only meant for hosting during development of the Chatroom frontend (Javascript / HTLM / CSS). 

Carefully, read the readme on how to integrate the Chatroom in you Rasa Core project: https://github.com/scalableminds/chatroom#simple-usage-with-a-custom-rasa-core-project-on-cli
