### ISSUE TITLE
bot doesn't reply 

### ISSUE THREAD

**Issue by e8180kimo** [scalableminds/chatroom#70]
I use my other computer to access my rasa bot. 
I have open the port 5005 on my local router. 
My other computer can open the website. However, when I type anything, the bot does not reply. It only replies on my local machine though.

**Comment by hotzenklotz** [comment]
Sorry, can't really help you with debugging your local network. Check you firewalls, see if you can access one computer from the other etc. 

We have the chatroom in use in several local networks and the internet without issues. Make sure to configure you network correctly.
