### ISSUE TITLE
Android UI for ChatBot using Rasa Core

### ISSUE THREAD

**Issue by AbrarAhmedQuresh** [scalableminds/chatroom#71]
Hello there,
I am able to add rasa_utils to my project and I am able to run the project successfully. I used this following steps,

1) First, I have added rasa_utils to my project and run it with the following command :

abrarahmed@abrarahmed-HP-Notebook:~/sql_troubleshooting$ python3 -m rasa_core.run --enable_api -d models/dialogue -u models/nlu/default/troubleshootnlu --port 5004 --credentials credentials.yml -o out.log

2) Once I run the above command i am successfully able to start the server :

2018-12-05 16:33:32 INFO     root  - Rasa Core server is up and running on http://localhost:5004

3) Then I pass the query with 'Hello'' with the curl command, and it responded back with "Hello! How can I help?" which is correct.

abrarahmed@abrarahmed-HP-Notebook:~/sql_troubleshooting$ curl -XPOST localhost:5004/conversations/default/respond -d '{"query":"Hello"}'

[{"recipient_id":"default","text":"Hello! How can I help?"}]

** My question is, instead of using UI as a web-based to interact with rasa core, How can I integrate with Android as a UI interface.

** My aim is to build a rasa-core bot which interacts with Android and capable of answering the questions based on provided Dataset.

Thanks in Advance.

**Comment by hotzenklotz** [comment]
This chatroom UI is a web component, designed to be integrated / embedded into a website. It is not meant to be included into an Android app.

Take a look the Rasa Core docs. You could use their [REST Channel](https://rasa.com/docs/core/connectors/#rest-channels) to integrate with your Android app.
