### ISSUE TITLE
Testing HTML snippet for Integrating with WordPress Site

### ISSUE THREAD

**Issue by vishnuragas** [scalableminds/chatroom#72]
Hi,

I tried to test the following code snippet by adding it to a sample WordPress post. Just to see the widget on the WordPress site. But when I pasted the code in WordPress and updated the site, the code reflected as 'plain text'. I am missing something here. 

How do I integrate the widget to the wordpress site? Should I use any custom .js codes for it to work? (I am new to HTML scripting and their elements, so I might be missing something obvious here)

Code I tested: 

```
<head>
  <link rel="stylesheet" href="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.css" />
</head>
<body>
  <div class="chat-container"></div>

  <script src="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.js"/></script>
  <script type="text/javascript">
    var chatroom = window.Chatroom({
      host: "http://localhost:5005",
      title: "Chat with Mike",
      container: document.querySelector(".chat-container"),
      welcomeMessage: "Hi, I am Mike. How may I help you?",
      speechRecognition: "en-US"
    });
    chatroom.openChat();
  </script>
</body>
```

**Comment by hotzenklotz** [comment]
I am not very familiar with Wordpress. I would assume that pasting HTML code into a new post will not be executed or anything. WP will most likely display it as `plain text`. 

In order to integrate the chatroom you need to directly manipulate the HTML / JS files of your WP instances. I am sure there are guide out there on how to include an iframe etc in your word press theme.

**Comment by vishnuragas** [comment]
@hotzenklotz Sorry, I was missing few details when I posted the issue. I did not just try to copy/paste the code to a blog section. I tried to insert the HTML snippet as a code to be shown on the blog page. 

On further research, found that 'wordpress.com' does not support javascript snippets to be added in their base free version. They requested to upgrade if I have to add javascript.

Our site runs using 'Wordpress.org' which is again different and looks like it allows javascript with the subscription that we have. However, on testing the snippet mentioned in the issue here, it does not show the widget on the page. (Tested sample HTML widget code from 'botsociety' tool  and it worked -widget popped up on the page). I would have to debug further to include iframe if it works.

**Comment by hotzenklotz** [comment]
Well, if the code is displayed a "plain text" on your wordpress site, then it is not executed at all. Looks like you need find the right WP files or setting.

Also, check your browsers developer tools and see if the scripts for the chatroom is actually downloaded / fetched on page load. The following JS file should be there: `https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.js`

**Comment by vishnuragas** [comment]
There was an error in the script. Checked for the JS script - https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.js and could see the UI element on the page after fixing it.
