### ISSUE TITLE
Using RASA HTTP API with chatroom issue

### ISSUE THREAD

**Issue by e8180kimo** [scalableminds/chatroom#76]
My rasa core is 0.11.12,  I am using [HTTP API GET](https://rasa.com/docs/core/0.11.12/server/?_ga=2.112103172.1446316257.1546230698-2005519191.1546230698#get--conversations-(str-sender_id)-tracker) to get the log conversation. The log file in my local machine did store the conversations, however, when I run the command:

curl http://localhost:5005/conversations/default/tracker | python -mjson.tool

It returns slot values as null and the sender_ID returned as “default”. Anyone know what’s going on there?

```
{
    "events": [
        {
            "event": "action",
            "name": "action_listen",
            "timestamp": 1545796214.6885061
        }
    ],
    "followup_action": null,
    "latest_event_time": 1545796214.6885061,
    "latest_input_channel": null,
    "latest_message": {
        "entities": [],
        "intent": {},
        "text": null
    },
    "paused": false,
    "sender_id": "default",
    "slots": {
        "requested_slot": null,
        "slot_against": null,
        "slot_agree": null,
        "slot_reason": null,
        "slot_thesis": null,
        "slot_topic": null
    }
```

I found there was [a similar issue](https://github.com/RasaHQ/rasa_core/issues/638#issuecomment-412812197), but as chatroom has updated, how should I fix this problem?
Happy New Year and thanks for the help.

**Comment by e8180kimo** [comment]
I think it might be the issue with register the agent for chatroom. When I did not use chatroom, I have no issues with HTTP API. 
In the instruction of advance usage:
`Register the BotServerInputChannel with your Rasa Core Agent`
Where should I include the code?

**Comment by hotzenklotz** [comment]
I am not sure I understand, what your problem is :-(

How do you usually start your bot? Can you confirm that the chatroom is actually running and working?

**Comment by e8180kimo** [comment]
@hotzenklotz 
I normally use [the simple usage](https://github.com/scalableminds/chatroom#simple-usage-with-a-custom-rasa-core-project-on-cli) by the command:

`python -m rasa_core.run --core models/dialogue --nlu models/current/nlu --endpoints endpoints.yml --credentials credentials.yml -d models/dialogue -u models/current/nlu -o out.log`

However, since I want to use their HTTP API, I added `--enable_api`, but as a result, the HTTP API GET does not return any result. That's why I thought the reason may be I did not use the advanced usage by register the rasa agent. 
If I did not use chatroom, I can use the HTTP API and got the conversation by using HTTP API GET.

But, after reading through the instruction, I still do not know how to register the rasa agent though. For instance, what file should I add the code? Please let me know if it's clear now. Thanks

**Comment by e8180kimo** [comment]
@hotzenklotz  I just made a python file and I place it with my rasa bot folder ( not inside rasa_utils folder).
Is this the right way to register the `agent`?
When I open a new terminal and use `python rasa_apagent.py`
It will run but I cannot run the next command to start my rasa server `python -m rasa_core.run --enable_api -d models/dialogue -u models/current/nlu --endpoints endpoints.yml --credentials credentials.yml -o out.log` ... because it says `port 5005 has been used`
Could you please tell me the right steps? Thanks

```
import os
from rasa_core.agent import Agent
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_utils.bot_server_channel import BotServerInputChannel

#Creating the Interpreter and Agent
def load_agent():
    nlu_interpreter = RasaNLUInterpreter('./models/current/nlu')
    agent = Agent()
    agent = Agent.load('./models/dialogue', interpreter = nlu_interpreter)
    
    return agent
    
#Creating the server
def main_server():
    agent = load_agent()

    channel = BotServerInputChannel(agent, port=5005)
    agent.handle_channels([channel], http_port=5005)


main_server()
```

**Comment by hotzenklotz** [comment]
You only need one method or the other to start the bot. Either `python rasa_apagent.py` or `python -m rasa_core.run ...`.

**Comment by e8180kimo** [comment]
hi @hotzenklotz if I want to use `python -m rasa_core.run --core models/dialogue --nlu models/current/nlu --endpoints endpoints.yml --credentials credentials.yml -d models/dialogue -u models/current/nlu -o out.log` , how can I register the agent according to the advanced usage?

**Comment by e8180kimo** [comment]
@hotzenklotz I tried to use `python rasa_apagent.py` and I revised the code. It can start the bot, but when I tried to pull out the log using HTTP API (python requests package), the bot stopped working.
I have no problem if just using the commandline for HTTP API though.

```
#Creating the Interpreter and Agent
def load_agent():
    nlu_interpreter = RasaNLUInterpreter('./models/current/nlu')
    action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")
    agent = Agent()
    agent = Agent.load('./models/dialogue', interpreter = nlu_interpreter, action_endpoint = action_endpoint)
    
    return agent
    
#Creating the server
def main_server():
    agent = load_agent()

    channel = BotServerInputChannel(agent, port=5005)
    agent.handle_channels([channel], http_port=5005)


main_server()
```

Part of the action.py code:
```
def submit(self, dispatcher, tracker, domain):
        
        agree_info = AgreeInfo()
        booking = agree_info.save(tracker.latest_message.get("text"))
        r = requests.get('http://localhost:5005/conversations/default/tracker')
        indexFile_senderid = open(str(tracker.latest_message.get("text")) + '.txt', 'w+', encoding='utf-8')
        indexFile_senderid.write('student ID: ' + tracker.latest_message.get("text") + str('\n\n') + str(r.content) + str('\n\n'))
 
        indexFile_senderid.close()
        return[]
```
