### ISSUE TITLE
Text to speech integration

### ISSUE THREAD

**Issue by adisdhiv** [scalableminds/chatroom#77]
I checked out the demo. It is doing speech recognition. Is it possible to add TTS integration with this? Like the output that the bot is replying, can it be converted to audio and sent to the user?

**Comment by hotzenklotz** [comment]
We don't plan on adding TTS anytime soon. There is no reliable open-source implementation for TTS yet. Browser support for speech input and output also varies greatly.

Feel free to fork the project and tinker with the Javascript to get TTS to work.
