### ISSUE TITLE
pass the button payload to rasa

### ISSUE THREAD

**Issue by sfrpl** [scalableminds/chatroom#79]
My domain.yml has
  utter_ask_gender:
  - buttons:
    - payload: /inform{"gender":"M"}
      title: Male
    - payload: /inform{"gender":"F"}
      title: Female
    - payload: /inform{"gender":"A"}
      title: No Preference

The button gets displayed in UI but when I click on the button
the payload is not getting passed to rasa

**Comment by hotzenklotz** [comment]
I am pretty certain it works. Make sure to use the right indentation and quotation for the markup. This works for me: 

``´
utter_hello_world:
  - text: "Are you happy?"
    buttons:
      - title: "Yes"
        payload: '/mood_affirm'
      - title: "No"
        payload: '/mood_deny'
```

**Comment by neerajb1** [comment]
Hi I am working on button. When i need to create some external link when user click it should redirect on that link . Is it available on UI  ?. How i can use it.
 utter_ask_menu:
  - buttons:
    - title: Google
      url: https://www.google.com/
    - title: Facebook
      url: https://www.facebook.com/
    - title: Youtube
      url: https://www.youtube.com/
    - payload: https://in.linkedin.com/
      title: Linekedin

**Comment by hotzenklotz** [comment]
You can use Markdown to create HTML links. E.g. `[Some Link](https://google.com)`. Markdown only works for the the "regular" bot response text.

Links a re not possible with buttons. The buttons are designed to work with the Rasa Stack's button API.

**Comment by NN123-Test** [comment]
> You can use Markdown to create HTML links. E.g. `[Some Link](https://google.com)`. Markdown only works for the the "regular" bot response text.
> 
> Links a re not possible with buttons. The buttons are designed to work with the Rasa Stack's button API.

Its not working :(

**Comment by gharshit192** [comment]
> Hi I am working on button. When i need to create some external link when user click it should redirect on that link . Is it available on UI ?. How i can use it.
> utter_ask_menu:
> 
> * buttons:
>   
>   * title: Google
>     url: https://www.google.com/
>   * title: Facebook
>     url: https://www.facebook.com/
>   * title: Youtube
>     url: https://www.youtube.com/
>   * payload: https://in.linkedin.com/
>     title: Linekedin

This is not working.

**Comment by hotzenklotz** [comment]
No, buttons can NOT link to external websites. A button click, will always send a message back to your Rasa bot. 

What you can do, however, is use Markdown and markdown links in your regular messages.  The Chatroom understand Markdown and will create clickable links. (just not buttons) 

e.g.
```
Hi, I am a chatbot. [Learn more about Rasa here.](www.rasa.com)
```

**Comment by pitoulambert** [comment]
> No, buttons can NOT link to external websites. A button click, will always send a message back to your Rasa bot.
> 
> What you can do, however, is use Markdown and markdown links in your regular messages. The Chatroom understand Markdown and will create clickable links. (just not buttons)
> 
> e.g.
> 
> ```
> Hi, I am a chatbot. [Learn more about Rasa here.](www.rasa.com)
> ```
