### ISSUE TITLE
yarn installationa

### ISSUE THREAD

**Issue by Ajinkz** [scalableminds/chatroom#80]
I was trying to install yarn changing current working directory to chatroom folder
`$ yarn install`

ERROR: [Errno 2] No such file or directory: 'install'
`

**Comment by hotzenklotz** [comment]
You need to execute `yarn install` in the root folder. It requires the `package.json`configuration file. This is the regular behavior of yarn. 

BTW, yarn is only required if you want to modify the HTML, JS, CSS of the webchat.
