### ISSUE TITLE
try to connect  chatroom with rasa

### ISSUE THREAD

**Issue by Robertjbc** [scalableminds/chatroom#81]
hi there, i have a issue, when i try to connect my chatbot to my website the bot don`t respond 

i am using the ngrok for create a http because i can't use the ip from the pc(for security), 

When I sent a response to the path of the ngrok plus the server I receive the answer that it supposes, but when I apply the script in the index.html the bot appears but it does not give me an answer

It should be noted that locally if it works

I need an answer urgently

regards 😉

**Comment by hotzenklotz** [comment]
> I need an answer urgently

Hi @Robertjbc, we provide professional tech consulting if you are interested. 

Otherwise, this sound like a networking issues on your side. Try Rasa's FB Messenger or Slack channel with NGrok and see if they work correctly.

**Comment by Robertjbc** [comment]
hello @hotzenklotz  thank for your answer, of course i`ll try the FB Messenger and Slack , i don`t have problem with those plataform, all worked perfectly, 

i also wonder if was a network problem (the firewall o any por that was blocked) but  that not the case 

also of that i see what the chat not worked with all rasa version so i wanna know  it`s the ultimate version of rasa is compatible with the chat if not what is the recommended version?

regards 😉

**Comment by hotzenklotz** [comment]
> i also wonder if was a network problem (the firewall o any por that was blocked) but that not the case

To eliminate the network as trouble maker, have you tested if it is working locally on your machine? 

> also of that i see what the chat not worked with all rasa version so i wanna know it`s the ultimate version of rasa is compatible with the chat if not what is the recommended version?

Version compatibility can be found in the README: https://github.com/scalableminds/chatroom#usage
Which Rasa Core and Chatroom versions are you running?

**Comment by hotzenklotz** [comment]
Version compatibility can be found in the README: https://github.com/scalableminds/chatroom#usage
Which Rasa Core and Chatroom versions are you running?

Feel free to open a Pull Request if you need to make changes to get it to run with a newer Rasa Core version.

**Comment by Robertjbc** [comment]
Hi @hotzenklotz ,
Do you have any video tutorial to install RASA core on Linux in youtube or other? 
I was reading that you company scalable minds implement chatbots, we are trying to create a test environment with RASA to create some chatbots for potential customers. I work for Capital Minds Inc. and my boss Raul Blanco may contact you company for support. 
Regards

**Comment by hotzenklotz** [comment]
No, we don't have a detailed video tutorial. All relevant information can be found in the readme of this project. 

If you need further assistance, we do offer commercial tech support for businesses as well. Let me know if this is interesting to you.

**Comment by ralmeron** [comment]
Hola Tom hope you are well, as Robert mention we are interested in creating a Rasa environment for testing use since we have some customers who want chatbots for different porpuses.

Let know how to contact you for support services.

**Comment by hotzenklotz** [comment]
@ralmeron Send me an email: tom.herold AT scalableminds.com
