### ISSUE TITLE
loop request to RASA

### ISSUE THREAD

**Issue by vinhphat89** [scalableminds/chatroom#82]
There are config of parameters:
const POLLING_INTERVAL = 1000;
const WAITING_TIMEOUT = 5000;

I just tested with:
```
      waitingTimeout: "5000",
      pollingInterval: "5000",
```

But it always make request to Rasa backend  every 5 seconds.
How can I make request to Rasa only when user submit the message? or fix this bug?

>  [2019-01-14 15:23:58] "GET /webhooks/chatroom/conversations/401afeab-0287-432a-a1f8-23f6d6f649c6/log?nocache=1547454238133 HTTP/1.1" 200 10516 0.002130
>  [2019-01-14 15:24:04] "GET /webhooks/chatroom/conversations/401afeab-0287-432a-a1f8-23f6d6f649c6/log?nocache=1547454244133 HTTP/1.1" 200 10516 0.002088
>  [2019-01-14 15:24:10] "GET /webhooks/chatroom/conversations/401afeab-0287-432a-a1f8-23f6d6f649c6/log?nocache=1547454250133 HTTP/1.1" 200 10516 0.002085
>  [2019-01-14 15:24:16] "GET /webhooks/chatroom/conversations/401afeab-0287-432a-a1f8-23f6d6f649c6/log?nocache=1547454256134 HTTP/1.1" 200 10516 0.002087
>  [2019-01-14 15:24:22] "GET /webhooks/chatroom/conversations/401afeab-0287-432a-a1f8-23f6d6f649c6/log?nocache=1547454262133 HTTP/1.1" 200 10516 0.002089
>  [2019-01-14 15:24:28] "GET /webhooks/chatroom/conversations/401afeab-0287-432a-a1f8-23f6d6f649c6/log?nocache=1547454268134 HTTP/1.1" 200 10516 0.002091
>  [2019-01-14 15:24:34] "GET /webhooks/chatroom/conversations/401afeab-0287-432a-a1f8-23f6d6f649c6/log?nocache=1547454274134 HTTP/1.1" 200 10516 0.002093
>  [2019-01-14 15:24:40] "GET /webhooks/chatroom/conversations/401afeab-0287-432a-a1f8-23f6d6f649c6/log?nocache=1547454280134 HTTP/1.1" 200 10516 0.002087
>  [2019-01-14 15:24:46] "GET /webhooks/chatroom/conversations/401afeab-0287-432a-a1f8-23f6d6f649c6/log?nocache=1547454286134 HTTP/1.1" 200 10516 0.002084
>  [2019-01-14 15:24:52] "GET /webhooks/chatroom/conversations/401afeab-0287-432a-a1f8-23f6d6f649c6/log?nocache=1547454292134 HTTP/1.1" 200 10516 0.002138
>  [2019-01-14 15:24:58] "GET /webhooks/chatroom/conversations/401afeab-0287-432a-a1f8-23f6d6f649c6/log?nocache=1547454298134 HTTP/1.1" 200 10516 0.002082
>  [2019-01-14 15:25:04] "GET /webhooks/chatroom/conversations/401afeab-0287-432a-a1f8-23f6d6f649c6/log?nocache=1547454304133 HTTP/1.1" 200 10516 0.004063

**Comment by hotzenklotz** [comment]
I am assuming the time interval configuration should be numbers not strings. Remove the "quotes".

**Comment by vinhphat89** [comment]
I see Chatroom using the polling technique. This always request to server until user click to button again to collapse the chat box.
I think we need update the the new option to prevent this. (request to server only when user submit and limit polling interval after a certain time).
In my case, I need bot reply to user only when user input a message immediately. And show something new from bot every day.
