### ISSUE TITLE
Not able to execute custom action .

### ISSUE THREAD

**Issue by Ajinkz** [scalableminds/chatroom#83]
`2019-01-14 16:52:33 INFO     root  - b'patron email verification'`
`2019-01-14 16:52:33 ERROR    rasa_core.processor  - Encountered an exception while running action 'action_faqs'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.`

**Comment by hotzenklotz** [comment]
Looks like an issues with your Rasa Core actions. See https://rasa.com/docs/core/customactions/

**Comment by harshitc** [comment]
If anyone is still searching the solution for this then make sure you are passing the --endpoints argument when running the bot.
