### ISSUE TITLE
Adjust buttons to only send their payload, not their title

### ISSUE THREAD

**Issue by bsaendig** [scalableminds/chatroom#84]
It seems like, when i press a button in the chatroom, not only the rasa command in the payload gets send to the Rasa core, but also a text message with the title of the button. Is it possible to change this behavior?
A speech bubble with the button text should still be shown to visualize the users choice, just the text should not be send to rasa.
How would i go about implementing that? I am very new to React.

Thanks in advance!

Here my code for the buttons:

buttons:
    - payload: '/Job_set{"specialty": "UX Design"}'
      title: "UX, Design"
    - payload: '/Job_set{"specialty": "Business Sales"}'
      title: "Business, Sales"

**Comment by hotzenklotz** [comment]
Not sure I understand your problem. 

I think the chatroom is working exactly how you describe it. The `payload` property gets send back to the bot while the `title` is displayed as a speech bubble.

**Comment by bsaendig** [comment]
I apologize. I think I misunderstood what the Rasa core was doing. It was not reacting the way I expected it to, but not because of the chatroom, but because it apparently has a problem with the slot filling in my example. Additionally, it showed a message that mislead me to believe, that only the title of the button got send.

rasa_core_1      | 2019-01-25 09:33:00 INFO     root  - b'Button_title'

But I tested it with a simpler intent in the payload and it worked. The core displays an info message showing the title but it reacts only to the payload.

I still have a problem with the slot filling but that does not belong here. I consider this issue closed.
