### ISSUE TITLE
Too much time to load rasa_utils.bot

### ISSUE THREAD

**Issue by shauryaparanjape** [scalableminds/chatroom#86]
Hi,

When I ran the rasa_utils.bot command as per the help page it started quickly. However, event hough when my hardware configuration has remained the same, the same command now runs very slowly. And also I am unable to see the bot on localhost:5005. It was working before but now it is broken.

I tried running the HTTP API and it is working fine, so I don't think there is a problem with the model. The bot.py keeps hanging up somewhere.

**Comment by hotzenklotz** [comment]
Try running your bot with a profiler (e.g. https://github.com/what-studio/profiling) to find the bottleneck. As your bot gets larger (more intents and more dialogues) it is expected that it will load slower. 

I am happy to review a pull request for any changes that make the chatroom adapter speedier.
