### ISSUE TITLE
[Question] Deactivate typing of answer to force user to click the button

### ISSUE THREAD

**Issue by eleow** [scalableminds/chatroom#87]
Is there some way for me to deactivate the box for typing when I am prompting the user to click the buttons, so that he will not enter some other unexpected input?

**Comment by hotzenklotz** [comment]
No, theres is no such functionality just yet. Feel free to add it and open pull request :-)

I guess the main motivation here was that Rasa has powerful natural language understanding end we didn't want to limit the users.

**Comment by eleow** [comment]
Sure.. Could I know roughly at which function of Chatroom.js would I add this?
Actually I need this because the buttons would have some additional actions associated with it that would not get triggered if it was typed in..

**Comment by hotzenklotz** [comment]
Well, marking the text input as `disabled` is best done in the `render` function. Perhaps you could check whether the last bot messages includes buttons and toggle the `disabled` property based on that.

**Comment by eleow** [comment]
Thank you! I have managed to get it working
- Added a new prop "disableInputOnButton" - If true, then we will disable text input if last bot message type is a button, and added corresponding css style to show "not-allowed".

Will open a pull request when I have a chance
