### ISSUE TITLE
No user interface or web page on server address http://localhost:5005

### ISSUE THREAD

**Issue by digitaShadow** [scalableminds/chatroom#94]
Hi
I am facing this issue where I have set up the servers by following the Advanced Usage with a custom Rasa Core project as Custom Channel from Python, but I am unable to figure out how do I use the interface on this server for the chat? Attaching the files, please help me out.

Thanks

[Rasa.zip](https://github.com/scalableminds/chatroom/files/2986528/Rasa.zip)

**Comment by jstriebel** [comment]
Simply open the `index.html` to open the Chat UI. `http://localhost:5005` is only to connect to the Rasa Core API, which is done by the UI.
