### ISSUE TITLE
Issue running webui with rasa

### ISSUE THREAD

**Issue by aizazqaisrani** [scalableminds/chatroom#97]
I am running rasa_core and rasa_nlu on docker compose. I can send message on http://localhost:5005 using curl and get response. Now I want to connect it with scalableminds. I am using the following code: 
`<head>
  <link rel="stylesheet" href="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.css" />
</head>
<body>
  <div class="chat-container"></div>

  <script src="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.js"/></script>
  <script type="text/javascript">
    window.chatroom = new window.Chatroom({
      host: "http://localhost:5005",
      title: "Chat with Mike",
      container: document.querySelector(".chat-container"),
      welcomeMessage: "Hi, I am Mike. How may I help you?",
      speechRecognition: "en-US"
    });
    chatroom.openChat();
  </script>
</body>
`

When I open it in browser, I get following error:

Unhandled promise rejection SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
Source map error: request failed with status 404
Resource URL: https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.js
Source Map URL: /Chatroom.map

Can you please guide me how to remove this issue?

Thanks

**Comment by jstriebel** [comment]
What curl commands did you use to test it? Did you include the [`rasa_utils`](https://github.com/scalableminds/chatroom#usage-with-a-standard-rasa-core-project) in you bot and start it with them or did you set it up in the `endpoints.yaml`?

PS: You can also try out #102, as this uses the standard Rasa Rest Channel.
