### ISSUE TITLE
Return image through custom actions

### ISSUE THREAD

**Issue by Chatzimina** [scalableminds/chatroom#99]
Hello,
can someone tell me if I can return an image through custom actions? What is the format of json and also should I use dispatcher.utter_message?

Also, is it possible to create a card or a carousel by adding to your existing code?

Thank you

**Comment by hotzenklotz** [comment]
Yes, you can use images. Rather then sending the image itself, just send the URL to a hosted version of the image. We typically have a corresponding template for the image. So you `dispatcher. utter_template()` or `dispatcher. utter_attachment()`. https://rasa.com/docs/core/api/dispatcher/

> Also, is it possible to create a card or a carousel by adding to your existing code?
Yes and no. Yes it can be done, but it is not straight forward: 
1. You would need to expand the HTML/CSS/JS for the carousel/card/UI element.
2. Expand the "communication protocol" between the React frontend and the bot channel.
3. (Extend Rasa Core to know the concept `card` etc. This only necessary if you want to have templates of type "card" etc. Not strictly necessary. You probably could get away with just passing special messages (e.g. "<CARD>") as strings and do some clever parsing.)

**Comment by Chatzimina** [comment]
Thank you for your quick answer. I have read about dispatcher. utter_template() or dispatcher. utter_attachment(). But I cannot find the correct json to add in order to return it. I tried :
         
     message = {"type": "image", "image": "http://www.heraklionmodellers.gr/wp-content/uploads/2019/03/afisa_for_header_03-215x215.jpg"}
or 

      message = {{"type":"image","payload":{ "title":"some title", "image_url":"http://www.heraklionmodellers.gr/wp-content/uploads/2019/03/afisa_for_header_03-215x215.jpg","subtitle":"subtitle!!"}}}

Can you give me an example?

For the card, I don't want something very special just a picture with a title and a button with a url. I believe I can do it through special messages that you are saying? This is inside your code I have to look?

Thank you and sorry if this questions are basic but I am new in rasa etc.

**Comment by hotzenklotz** [comment]
> Thank you for your quick answer. I have read about dispatcher. utter_template() or dispatcher. utter_attachment(). But I cannot find the correct json to add in order to return it. I tried 

Not sure I understand what you are trying to do. There is two ways of sending messages based on templates. Either as defined in a story or using custom actions (e.g. with Rasa Core SDK).

As a custom action using the Rasa Core SDK
```
from rasa_core_sdk import Action
class SomeAction(Action):

    def name(self):
        return "actionmy_action"

    def run(self, dispatcher, tracker, domain):
         dispatcher.utter_template("utter_my_image_template", tracker)
```

As regular story: 
```
* get_some_intent
    - utter_my_image_template
```

>For the card, I don't want something very special just a picture with a title and a button with a url. I believe I can do it through special messages that you are saying? This is inside your code I have to look?
We don't have this feature. Feel free to add it and open a PR.

**Comment by Chatzimina** [comment]
ok thank you
